### PR TITLE
Prevent error when terminal.processId is -1

### LINKED ISSUE #10: Error on M1 MacBook Pro when moving focus to another application
I recently got an updated work machine and it's got an M1 processor in it. Since I set up VSCode and transferred all my settings and extensions across, I've started getting the following error in VSCode's notification area:

```
Error while listening for process end: Error: Command failed: ps -o tty -1 ps: illegal option -- 1 usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]] [-g grp[,grp...]] [-u [uid,uid...]] [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]] ps [-L] ,ps: illegal option -- 1 usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]] [-g grp[,grp...]] [-u [uid,uid...]] [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]] ps [-L]
```

image

The extension still works despite this error, but the error notification itself is very obtrusive. If I have long-running tasks I just end up leaving the notification there as it will just pop back up again when I shift focus to my browser or another application.

### PR DESCRIPTION
**Pull request by andyearnshaw**
Fixes #10

### CODE REVIEW

**Comment by brynshanahan** [comment]
Hey @andyearnshaw do you know how I can use your fix with this extension?

**Comment by brynshanahan** [comment]
Never mind. 

I got rid of the error by modifying the source file in `.vscode/extensions/extID/index.js` 👍

Had to add
```js
const pid = await terminal.processId;
if (pid === -1) return 
```

**Comment by jaredly** [comment]
thanks!

**Comment by ryanparker-st** [comment]
CleanShot 2025-01-10 at 13 04 04@2x

Still seeing this even with the recommended change: https://github.com/jaredly/vscode-background-terminal-notifier/pull/11#issuecomment-1562394578

**Pull request merged**
